---
name: Catalyst-Plugin-Static-Simple
version: 0.12
author:
  - 'Andy Grundman, <andy@hybridized.org>'
abstract: Make serving static pages painless.
license: perl
requires:
  Catalyst: 5.30
  MIME::Types: 1.15
provides:
  Catalyst::Plugin::Static::Simple:
    file: lib/Catalyst/Plugin/Static/Simple.pm
    version: 0.12
generated_by: Module::Build version 0.26
