--- #YAML:1.0
name: Catalyst-Plugin-Static-Simple
version: 0.15
author:
  - Andy Grundman, <andy@hybridized.org>
abstract: Make serving static pages painless.
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
